import json
import pathlib
import common
import magic


def spell_key(name: str, tags: list[str]) -> str:
    return " -- ".join([name.lower().strip()] + [t.lower().strip() for t in tags])


def build_spell_index() -> dict[str, str]:
    index: dict[str, str] = {}
    for s in magic.school_settings:
        public = common.parse_magic_file(pathlib.Path(f"lists/{s.filename}.txt"))
        secret = common.parse_magic_file_s(
            common.parse_secrets(s.filename), secret=True
        )
        for school in (public, secret):
            for spell in school.spells_flat():
                key = spell_key(spell.name, spell.tags)
                # spell_to_markdown() prefixes "* " for the bulleted list rendering;
                # strip it since here the HTML is inlined inside character text.
                index[key] = magic.spell_to_markdown(spell)[2:]
    return index


def generate_js(index: dict[str, str]) -> str:
    lookup_json = json.dumps(index, ensure_ascii=False, indent=2)
    return f"""// Auto-generated by character.py - do not edit by hand.
var SPELL_LOOKUP = {lookup_json};
function parse_spell_name(spell_name) {{
    var key = spell_name.split('--').map(function (p) {{ return p.trim().toLowerCase(); }}).join(' -- ');
    return SPELL_LOOKUP[key] || '<span>Error</span>';
}}
"""


def main():
    index = build_spell_index()
    out_path = pathlib.Path("DrusMagie/static/js")
    out_path.mkdir(parents=True, exist_ok=True)
    (out_path / "character_spells.js").write_text(generate_js(index))


if __name__ == "__main__":
    main()
