import json
import pathlib
import shutil
import unicodedata
import common
import magic


def normalize(s: str) -> str:
    stripped = "".join(
        c for c in unicodedata.normalize("NFD", s.lower().strip())
        if unicodedata.category(c) != "Mn"
    )
    return unicodedata.normalize("NFC", stripped)


def build_spell_index() -> dict[str, list[dict]]:
    # name -> list of {tags, html}, since the same name can have several tag variants.
    index: dict[str, list[dict]] = {}
    for s in magic.school_settings:
        public = common.parse_magic_file(pathlib.Path(f"lists/{s.filename}.txt"))
        secret = common.parse_magic_file_s(
            common.parse_secrets(s.filename), secret=True
        )
        for school in (public, secret):
            for spell in school.spells_flat():
                name_key = normalize(spell.name)
                # spell_to_markdown() prefixes "* " for the bulleted list rendering;
                # strip it since here the HTML is inlined inside character text.
                html = magic.spell_to_markdown(spell)[2:]
                index.setdefault(name_key, []).append(
                    {"tags": [normalize(t) for t in spell.tags], "html": html}
                )
    return index


def generate_js(index: dict[str, list[dict]]) -> str:
    lookup_json = json.dumps(index, ensure_ascii=False, indent=2)
    return f"""// Auto-generated by character.py - do not edit by hand.
var SPELL_LOOKUP = {lookup_json};
function normalize(s) {{
    return s.normalize('NFD').replace(/[\\u0300-\\u036f]/g, '').toLowerCase().trim();
}}
function parse_spell_name(spell_name) {{
    var parts = spell_name.split('--').map(normalize);
    var name = parts[0];
    var tags = parts.slice(1);
    var candidates = SPELL_LOOKUP[name] || [];
    for (var i = 0; i < candidates.length; i++) {{
        var candidate = candidates[i];
        if (tags.every(function (t) {{ return candidate.tags.indexOf(t) !== -1; }})) {{
            return candidate.html;
        }}
    }}
    return '<span>Error</span>';
}}
"""


def main():
    index = build_spell_index()
    out_path = pathlib.Path("DrusMagie/static/js")
    out_path.mkdir(parents=True, exist_ok=True)
    (out_path / "character_spells.js").write_text(generate_js(index))

    content_path = pathlib.Path("DrusMagie/content/magic")
    content_path.mkdir(parents=True, exist_ok=True)
    for name in ("postava.md", "postava_nahled.md"):
        shutil.copyfile(f"templates/{name}", content_path / name)


if __name__ == "__main__":
    main()
