name: Hue Hue Hue

on:
  push:
    branches:
      - master

jobs:
  build_drus_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update apt
        run: sudo apt-get update
      - name: Download Hugo
        run: sudo apt-get install hugo
      - name: Test Hugo
        run: hugo version 
      - name: Final
        run: echo "Finished!"

