name: Hue Hue Hue

on:
  push:
    branches:
      - master

jobs:
  build_drus_website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update apt
        run: sudo apt-get update -qq
      - name: Download Hugo
        run: sudo apt-get install hugo python3
      - name: Build server
        run:  cd $GITHUB_WORKSPACE
      - name: Update spell contents
        run: python3 spell_contents.py
      - name: Build server
        run: cd DrusMagie && hugo
      - name: Create dir
        run: mkdir ../../deploy
      - name: Copy over
        run: cp -r $GITHUB_WORKSPACE/DrusMagie/public ../../deploy
      - name: Move over
        run: cd ../../deploy
      - name: Upload to github
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Built-in token for same-repo operations
          publish_dir: ../../deploy/public # The directory to publish
          publish_branch: github-pages # The target branch
          user_name: 'github-actions[bot]' # Recommended bot name
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploying the Drus Site (Based) 😉'
