name: Hue Hue Hue

on:
  push:
    branches:
      - master

jobs:
  build_drus_website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update apt
        run: sudo apt-get update -qq
      - name: Download Hugo
        run: sudo apt-get install -q hugo python3
      - name: Change dir
        run: cd $GITHUB_WORKSPACE
      - name: Update spell contents
        run: python3 spell_contents.py
      - name: Build server
        run: cd DrusMagie && hugo --baseURL "https://drusrpg.github.io"
      - name: Upload to github
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Built-in token for same-repo operations
          publish_dir: . # The directory to publish
          publish_branch: github-pages # The target branch
          user_name: 'Mistr vodíkové bomby[bot]' # Recommended bot name
          user_email: '╰(*°▽°*)╯[bot]@chad.org'
          commit_message: 'Deploying the Drus Site (Based) 😉'
